In [1]:
pip install kaggle

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv('MIT-BIH_preprocessed.csv')
data.shape

(107775, 182)

In [4]:
data.head()

Unnamed: 0         0         1         2         3         4         5  \
0           0  0.006723 -0.019156  0.032603  0.006723  0.084363  0.032603   
1           1 -0.122676 -0.200316 -0.200316 -0.252076 -0.226196 -0.174436   
2           2 -0.355596 -0.407356 -0.252076 -0.277956 -0.252076 -0.277956   
3           3 -0.200316 -0.200316 -0.226196 -0.252076 -0.200316 -0.122676   
4           4 -0.174436 -0.174436 -0.174436 -0.096796 -0.096796 -0.096796   

          6         7         8  ...       171       172       173       174  \
0  0.032603  0.006723  0.006723  ... -0.536756 -0.562636 -0.614396 -0.588516   
1 -0.122676 -0.174436 -0.174436  ... -0.562636 -0.510876 -0.510876 -0.536756   
2 -0.277956 -0.329716 -0.277956  ... -0.329716 -0.355596 -0.407356 -0.433236   
3 -0.122676 -0.148556 -0.148556  ... -0.614396 -0.614396 -0.614396 -0.588516   
4 -0.200316 -0.226196 -0.174436  ... -0.459116 -0.459116 -0.510876 -0.536756   

        175       176       177       178       179  target  
0 -0.666156 -0.640276 -0.640276 -0.588516 -0.640276       1  
1 -0.562636 -0.588516 -0.588516 -0.614396 -0.562636       1  
2 -0.433236 -0.355596 -0.303836 -0.407356 -0.381476       1  
3 -0.614396 -0.743796 -0.717916 -0.743796 -0.666156       1  
4 -0.614396 -0.614396 -0.536756 -0.536756 -0.588516       1  

[5 rows x 182 columns]

In [5]:
x=data.iloc[:,1:]
y=data[['target']]


In [6]:
x.head()

0         1         2         3         4         5         6  \
0  0.006723 -0.019156  0.032603  0.006723  0.084363  0.032603  0.032603   
1 -0.122676 -0.200316 -0.200316 -0.252076 -0.226196 -0.174436 -0.122676   
2 -0.355596 -0.407356 -0.252076 -0.277956 -0.252076 -0.277956 -0.277956   
3 -0.200316 -0.200316 -0.226196 -0.252076 -0.200316 -0.122676 -0.122676   
4 -0.174436 -0.174436 -0.174436 -0.096796 -0.096796 -0.096796 -0.200316   

          7         8         9  ...       171       172       173       174  \
0  0.006723  0.006723  0.084363  ... -0.536756 -0.562636 -0.614396 -0.588516   
1 -0.174436 -0.174436 -0.174436  ... -0.562636 -0.510876 -0.510876 -0.536756   
2 -0.329716 -0.277956 -0.200316  ... -0.329716 -0.355596 -0.407356 -0.433236   
3 -0.148556 -0.148556 -0.174436  ... -0.614396 -0.614396 -0.614396 -0.588516   
4 -0.226196 -0.174436 -0.122676  ... -0.459116 -0.459116 -0.510876 -0.536756   

        175       176       177       178       179  target  
0 -0.666156 -0.640276 -0.640276 -0.588516 -0.640276       1  
1 -0.562636 -0.588516 -0.588516 -0.614396 -0.562636       1  
2 -0.433236 -0.355596 -0.303836 -0.407356 -0.381476       1  
3 -0.614396 -0.743796 -0.717916 -0.743796 -0.666156       1  
4 -0.614396 -0.614396 -0.536756 -0.536756 -0.588516       1  

[5 rows x 181 columns]

In [7]:
# y.value_counts()

In [8]:
# y.replace(['VEB','SVEB','F','Q'],'Arrhythmia',inplace=True)
# y.replace(['N'],'Normal',inplace=True)

In [9]:
# y.value_counts()

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=101)


In [19]:
y_train

target
22151        1
100574       3
87680        1
66886        1
8389         1
...        ...
5695         2
73542        0
83281        1
83467        1
45919        1

[80831 rows x 1 columns]

In [11]:
from sklearn import preprocessing
min_max_scaler=preprocessing.MinMaxScaler()
x_train_scaled=min_max_scaler.fit_transform(x_train)
x_test_scaled=min_max_scaler.transform(x_test)
print(min_max_scaler.scale_)

[0.05335644 0.0533923  0.05333365 0.05325077 0.05300367 0.05242492
 0.05216204 0.05228688 0.05250365 0.0529202  0.05268726 0.05286096
 0.05242175 0.05268726 0.05281464 0.05276839 0.05296671 0.05272223
 0.05231974 0.05241075 0.05237619 0.05230721 0.05223841 0.05224934
 0.0519326  0.05197739 0.05180944 0.05212467 0.05214801 0.05203466
 0.05227279 0.0521589  0.05228373 0.05250047 0.05231659 0.0521231
 0.05200986 0.05197583 0.05223684 0.05238559 0.05216979 0.05201142
 0.05195421 0.05196502 0.05197583 0.05222434 0.05220093 0.05199748
 0.05204238 0.05220093 0.05232597 0.05220093 0.05224619 0.05208736
 0.05153897 0.05170517 0.05186168 0.05222277 0.05215419 0.05192793
 0.0514934  0.05133911 0.05162574 0.05181554 0.05133911 0.05080629
 0.0502526  0.04985549 0.04993812 0.0504528  0.05090247 0.05129389
 0.05125027 0.05169293 0.05249729 0.05423059 0.05485187 0.05449101
 0.05335151 0.05225712 0.05050675 0.04878934 0.04763502 0.04790005
 0.04969525 0.05171347 0.04954234 0.04748652 0.04596452 0.04465

In [12]:
x_train_scaled

array([[0.53092694, 0.53424704, 0.53839008, ..., 0.50693734, 0.50525206,
        0.25      ],
       [0.53899377, 0.54671103, 0.55199634, ..., 0.50603736, 0.50488415,
        0.75      ],
       [0.54879529, 0.55271283, 0.55564718, ..., 0.46545784, 0.46296073,
        0.25      ],
       ...,
       [0.55002952, 0.55080093, 0.55188335, ..., 0.41505805, 0.41095732,
        0.25      ],
       [0.59261484, 0.59341487, 0.59735279, ..., 0.47503448, 0.47029157,
        0.25      ],
       [0.52769471, 0.52893535, 0.53216404, ..., 0.40449595, 0.40325861,
        0.25      ]])

In [13]:
#Random Forest train 
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(random_state=101,n_estimators=150)
model.fit(x_train_scaled,y_train)
print('Accuracy for the train data',model.score(x_train_scaled,y_train))


C:\Users\student\AppData\Local\Temp\ipykernel_15500\25360891.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(x_train_scaled,y_train)


Accuracy for the train data 1.0


In [14]:
#Logistic Regression train
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression(random_state=101,solver='lbfgs', max_iter=1000)
clf.fit(x_train_scaled,y_train)
print('Accuracy for the train data',model.score(x_train_scaled,y_train))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy for the train data 1.0


In [15]:
#Random Forest predict
from sklearn import metrics
y_pred=model.predict(x_test_scaled)
print('Accuracy',metrics.accuracy_score(y_test,y_pred))
print('Confusion Metrics')
print(metrics.confusion_matrix(y_test,y_pred))

Accuracy 0.9979958432304038
Confusion Metrics
[[  154    28     0     0     0]
 [    0 22532     1     0     0]
 [    0     2  1942     3     3]
 [    0     3     0   653     7]
 [    0     2     0     5  1609]]


In [16]:
#Logistic Regression Predict
from sklearn import metrics
y_pred2=clf.predict(x_test_scaled)
print('Accuracy',metrics.accuracy_score(y_test,y_pred2))
print('Confusion Metrics')
print(metrics.confusion_matrix(y_test,y_pred))

Accuracy 0.9979216152019003
Confusion Metrics
[[  154    28     0     0     0]
 [    0 22532     1     0     0]
 [    0     2  1942     3     3]
 [    0     3     0   653     7]
 [    0     2     0     5  1609]]


In [18]:
#SVM model
from sklearn.svm import SVC
svc=SVC()
svc.fit(x_train_scaled,y_train)
y_pred=svc.predict(x_test_scaled)
print('accuracy score;- ',metrics.accuracy_score(y_test,y_pred))
print(metrics.confusion_matrix(y_test,y_pred))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


accuracy score;-  0.9995546318289786
[[  181     1     0     0     0]
 [    0 22533     0     0     0]
 [    0     4  1946     0     0]
 [    0     2     0   661     0]
 [    0     5     0     0  1611]]
